controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    rover_controller:
      type: diff_drive_controller/DiffDriveController

    # Revolute_14_effort_controller:
    #   type: effort_controllers/JointEffortController

    # Revolute_15_effort_controller:
    #   type: effort_controllers/JointEffortController

    # Revolute_16_effort_controller:
    #   type: effort_controllers/JointEffortController

    # Revolute_17_effort_controller:
    #   type: effort_controllers/JointEffortController

rover_controller:
  ros__parameters:
    publish_rate: 50.0
    base_frame_id: base_footprint
    left_wheel_names: ["wheel_back_left_joint", "wheel_front_left_joint"]
    right_wheel_names: ["wheel_back_right_joint", "wheel_front_right_joint"]
    wheel_separation: 0.7
    wheel_radius: 0.123
    use_stamped_vel: true
    wheels_per_side: 2
    max_linear_velocity: 0.5
    min_linear_velocity: -0.5
    max_angular_velocity: 1.0
    min_angular_velocity: -1.0
    odom_topic: encoder

# # Effort controllers for each wheel joint
# Revolute_14_effort_controller:
#   ros__parameters:
#     joint: "Revolute 14"
#     pid:
#       p: 100.0
#       i: 0.01
#       d: 10.0

# Revolute_15_effort_controller:
#   ros__parameters:
#     joint: "Revolute 15"
#     pid:
#       p: 100.0
#       i: 0.01
#       d: 10.0

# Revolute_16_effort_controller:
#   ros__parameters:
#     joint: "Revolute 16"
#     pid:
#       p: 100.0
#       i: 0.01
#       d: 10.0

# Revolute_17_effort_controller:
#   ros__parameters:
#     joint: "Revolute 17"
#     pid:
#       p: 100.0
#       i: 0.01
#       d: 10.0
